language: php

php:
  - 5.3

env:
  - DB=MYSQL CORE_RELEASE=3.1

before_script:
  - composer self-update
  - phpenv rehash
  - git clone git://github.com/Sunny-Side-Up/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
 - php framework/cli-script.php dev/build


# configure notifications (email, IRC, campfire etc)
notifications:
  email: ssuerrors@gmail.com
